// <auto-generated />
using IMSWebApp.Models.DataModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace IMSWebApp.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IMSWebApp.Models.DataModel.DAILY_LOG", b =>
                {
                    b.Property<int>("ID_PK")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("COMMENT");

                    b.Property<DateTime>("DAILY_DATE");

                    b.Property<int>("LOG_FK");

                    b.Property<int?>("MORTALITYID_PK");

                    b.Property<int>("QTY");

                    b.Property<int>("REASON_FK");

                    b.Property<int?>("TANK_LOGID_PK");

                    b.HasKey("ID_PK");

                    b.HasIndex("MORTALITYID_PK");

                    b.HasIndex("TANK_LOGID_PK");

                    b.ToTable("DAILY_LOG");
                });

            modelBuilder.Entity("IMSWebApp.Models.DataModel.MORTALITY", b =>
                {
                    b.Property<int>("ID_PK")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("TEXT");

                    b.HasKey("ID_PK");

                    b.ToTable("MORTALITY");
                });

            modelBuilder.Entity("IMSWebApp.Models.DataModel.SPECIES", b =>
                {
                    b.Property<int>("ID_PK")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("COMMON");

                    b.Property<string>("SCIENTIFIC");

                    b.HasKey("ID_PK");

                    b.ToTable("SPECIES");
                });

            modelBuilder.Entity("IMSWebApp.Models.DataModel.TANK_LOG", b =>
                {
                    b.Property<int>("ID_PK")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("COMMENT");

                    b.Property<DateTime>("PERIOD_DATE");

                    b.Property<int>("QTY");

                    b.Property<int?>("SPECIESID_PK");

                    b.Property<int>("SPECIES_FK");

                    b.Property<int>("TANK_ID");

                    b.HasKey("ID_PK");

                    b.HasIndex("SPECIESID_PK");

                    b.ToTable("TANK_LOG");
                });

            modelBuilder.Entity("IMSWebApp.Models.DataModel.DAILY_LOG", b =>
                {
                    b.HasOne("IMSWebApp.Models.DataModel.MORTALITY", "MORTALITY")
                        .WithMany("DAILY_LOG")
                        .HasForeignKey("MORTALITYID_PK");

                    b.HasOne("IMSWebApp.Models.DataModel.TANK_LOG", "TANK_LOG")
                        .WithMany("DAILY_LOG")
                        .HasForeignKey("TANK_LOGID_PK");
                });

            modelBuilder.Entity("IMSWebApp.Models.DataModel.TANK_LOG", b =>
                {
                    b.HasOne("IMSWebApp.Models.DataModel.SPECIES", "SPECIES")
                        .WithMany("TANK_LOG")
                        .HasForeignKey("SPECIESID_PK");
                });
#pragma warning restore 612, 618
        }
    }
}
