// <auto-generated />
using IMSWebApp.Models.DataModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace IMSWebApp.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IMSWebApp.Models.DataModel.DAILY_LOG", b =>
                {
                    b.Property<int>("ID_PK")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("COMMENT")
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DAILY_DATE")
                        .HasColumnType("datetime");

                    b.Property<int>("LOG_FK");

                    b.Property<int>("QTY");

                    b.Property<int>("REASON_FK");

                    b.Property<int?>("TANK_LOGID_PK1");

                    b.HasKey("ID_PK");

                    b.HasIndex("LOG_FK")
                        .IsUnique();

                    b.HasIndex("REASON_FK");

                    b.HasIndex("TANK_LOGID_PK1");

                    b.ToTable("DAILY_LOG");
                });

            modelBuilder.Entity("IMSWebApp.Models.DataModel.MORTALITY", b =>
                {
                    b.Property<int>("ID_PK")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("TEXT")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID_PK");

                    b.ToTable("MORTALITY");
                });

            modelBuilder.Entity("IMSWebApp.Models.DataModel.SPECIES", b =>
                {
                    b.Property<int>("ID_PK")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("COMMON")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SCIENTIFIC")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID_PK");

                    b.ToTable("SPECIES");
                });

            modelBuilder.Entity("IMSWebApp.Models.DataModel.TANK_LOG", b =>
                {
                    b.Property<int>("ID_PK")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("COMMENT")
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("PERIOD_DATE")
                        .HasColumnType("datetime");

                    b.Property<int>("QTY");

                    b.Property<int>("SPECIES_FK");

                    b.Property<int>("TANK_ID");

                    b.HasKey("ID_PK");

                    b.HasIndex("SPECIES_FK");

                    b.ToTable("TANK_LOG");
                });

            modelBuilder.Entity("IMSWebApp.Models.DataModel.DAILY_LOG", b =>
                {
                    b.HasOne("IMSWebApp.Models.DataModel.TANK_LOG", "TANK_LOG")
                        .WithOne()
                        .HasForeignKey("IMSWebApp.Models.DataModel.DAILY_LOG", "LOG_FK")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IMSWebApp.Models.DataModel.MORTALITY", "MORTALITY")
                        .WithMany("DAILY_LOG")
                        .HasForeignKey("REASON_FK")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IMSWebApp.Models.DataModel.TANK_LOG")
                        .WithMany("DAILY_LOG")
                        .HasForeignKey("TANK_LOGID_PK1");
                });

            modelBuilder.Entity("IMSWebApp.Models.DataModel.TANK_LOG", b =>
                {
                    b.HasOne("IMSWebApp.Models.DataModel.SPECIES", "SPECIES")
                        .WithMany("TANK_LOG")
                        .HasForeignKey("SPECIES_FK")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
